language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew

script:
  - ./gradlew test --info

# cache gradle dependencies
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
